services:
  db:
    image: mysql:8
    networks:
      - net

  bref-app:
    image: bref-app
    container_name: bref-app
    build:
      context: .
      dockerfile: Dockerfile
      target: bref
      args:
        PHP_VERSION_TAG: ${PHP_VERSION_TAG:-8.1}
        PHP_VERSION: ${PHP_VERSION:-81}
        PHP_LARAVEL_TAG: ${PHP_LARAVEL_TAG:-11.*}
    networks:
      - net
    ports:
      - 9090:8080
    volumes:
      - ./:/var/task/vendor/datpmwork/sls-tinker/
    command:
      - artisan

  vapor-app:
    image: vapor-app
    container_name: vapor-app
    build:
      context: .
      dockerfile: Dockerfile
      target: vapor
      args:
        PHP_VERSION_TAG: ${PHP_VERSION_TAG:-8.1}
        PHP_VERSION: ${PHP_VERSION:-81}
        PHP_LARAVEL_TAG: ${PHP_LARAVEL_TAG:-11.*}
    networks:
      - net
    ports:
      - 9091:8080
    volumes:
      - ./:/var/task/vendor/datpmwork/sls-tinker/
    command:
      - artisan

networks:
  net:
    driver: "bridge"
